import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <Providers>
          <main className="max-w-5xl my-0 mx-auto font-urbanist text-small md:text-screenSmall flex flex-col justify-center items-center text-balance">
            {" "}
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
